const AVENGERS_FETCH_REQUEST = 'AVENGERS_FETCH_REQUEST';
const AVENGERS_FETCH_SUCCESS = 'AVENGERS_FETCH_SUCCESS';
const AVENGERS_FETCH_ERROR = 'AVENGERS_FETCH_ERROR';

export default {
  AVENGERS_FETCH_REQUEST,
  AVENGERS_FETCH_SUCCESS,
  AVENGERS_FETCH_ERROR,
};
